[[mgr.prepend_keymap]]
on = [ "<Enter>" ]
run = '''shell 'nvim "$1"' --block'''

[[mgr.prepend_keymap]]
on = [ "b", "w" ]
run = "cd ~/dev/adler.games"
desc = "Go to adler"

[[mgr.prepend_keymap]]
on = [ "b", "m" ]
run = "cd /etc/nix-darwin/"
desc = "Go to nix-darwin"

[[mgr.prepend_keymap]]
on = [ "b", "d" ]
run = "cd ~/dev"
desc = "Go to dev"


[[mgr.prepend_keymap]]
on = [ "u", "a" ]
run = "plugin yamb save"
desc = "Add bookmark"

[[mgr.prepend_keymap]]
on = [ "u", "g" ]
run = "plugin yamb jump_by_key"
desc = "Jump bookmark by key"

[[mgr.prepend_keymap]]
on = [ "u", "G" ]
run = "plugin yamb jump_by_fzf"
desc = "Jump bookmark by fzf"

[[mgr.prepend_keymap]]
on = [ "u", "d" ]
run = "plugin yamb delete_by_key"
desc = "Delete bookmark by key"

[[mgr.prepend_keymap]]
on = [ "u", "D" ]
run = "plugin yamb delete_by_fzf"
desc = "Delete bookmark by fzf"

[[mgr.prepend_keymap]]
on = [ "u", "A" ]
run = "plugin yamb delete_all"
desc = "Delete all bookmarks"

[[mgr.prepend_keymap]]
on = [ "u", "r" ]
run = "plugin yamb rename_by_key"
desc = "Rename bookmark by key"

[[mgr.prepend_keymap]]
on = [ "u", "R" ]
run = "plugin yamb rename_by_fzf"
desc = "Rename bookmark by fzf"
